Repository juami/pytentiostat, pull requests merged in 2019-11, with the labels that each got.

#90 Keyboard interrupt
  pytentiostat/config_reader.py
  pytentiostat/main.py
  pytentiostat/reporter.py
  pytentiostat/routines.py
  pytentiostat/tester.py
Labels: enhancement

#105 adding docstrings for tester and routines
  pytentiostat/config_reader.py
  pytentiostat/plotter.py
  pytentiostat/reporter.py
  pytentiostat/routines.py
  pytentiostat/tester.py
Labels: documentation

#104 moving interrupt earlier in the loop
  pytentiostat/tester.py
Labels: bug, enhancement

#115 redoing_tester_refactor
  pytentiostat/config.yml
  pytentiostat/main.py
  pytentiostat/operator.py
Labels: style

#122 changing labels
  GUI/code/CA_GUI.py
  GUI/code/CV_GUI.py
  GUI/code/LSV_GUI.py
  GUI/designer_files/CA_gui.ui
  GUI/designer_files/CV_gui.ui
  GUI/designer_files/LSV.ui
Labels: style

#125 Rename 'delete' button with 'remove'
  GUI/code/GUI_file_operation.py
  GUI/code/main.py
  GUI/code/mainwindow_GUI.py
Labels: style

#106 adding in config reader a check for all the parameters
  pytentiostat/config_reader.py
  pytentiostat/reporter.py
  tests/static/adv_config.yml
  tests/static/config.yml
Labels: documentation, enhancement, help wanted
